version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret123
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret123
      - MYSQL_ROOT_PASSWORD=secret123
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel
      - PMA_PASSWORD=secret123
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  worker:
    build: .
    command: php artisan queue:work redis --tries=3
    environment:
      - APP_KEY=${APP_KEY}
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret123
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis
      - app

volumes:
  mysql_data:
  redis_data:
